apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata: 
  name: testing
  namespace: argocd
spec:
  description: A testing project.
  destinations:
  - name: '*',
    namespace: '*',
    server: https://kubernetes.default.svc
  sourceRepos:
  - https://github.com/zachseifts/argocd-test.git
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testing-test
  namespace: argocd
spec:
  destination:
    namespace: testing-dev
    server: https://kubernetes.default.svc
  project: testing
  source:
    path: test
    repoURL: https://github.com/zachseifts/argocd-test.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testing-stage
  namespace: argocd
spec:
  destination:
    namespace: testing-stage
    server: https://kubernetes.default.svc
  project: testing
  source:
    path: stage
    repoURL: https://github.com/zachseifts/argocd-test.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testing-prod
  namespace: argocd
spec:
  destination:
    namespace: testing-prod
    server: https://kubernetes.default.svc
  project: testing
  source:
    path: prod
    repoURL: https://github.com/zachseifts/argocd-test.git
    targetRevision: HEAD
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
