apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata: 
  name: weather-dev
  namespace: argocd
spec:
  description: A development environment for the weather project.
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - name: '*'
    namespace: '*'
    server: https://kubernetes.default.svc
  sourceRepos:
  - https://github.com/zachseifts/argocd-test.git
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: weather-dev
spec:
  generators:
  - list:
      elements:
      - cluster: dev
        url: https://kubernetes.default.svc
        namespace: weather-dev
      - cluster: stage
        url: https://kubernetes.default.svc
        namespace: weather-stage
  template:
    metadata:
      name: 'weather-{{cluster}}'
    spec:
      project: weather-dev
      source:
        repoURL: https://github.com/zachseifts/argocd-test.git
        targetRevision: HEAD
        path: environments/{{cluster}}
      destination:
        server: '{{url}}'
        namespace: '{{namespace}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
