apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata: 
  name: weather-dev
  namespace: argocd
spec:
  description: A development environment for the weather project.
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - name: '*'
    namespace: '*'
    server: https://kubernetes.default.svc
  sourceRepos:
  - https://github.com/zachseifts/argocd-test.git
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: weather-dev
spec:
  generators:
  - git:
      repoURL: https://github.com/zachseifts/argocd-test.git
      revision: HEAD
      directories:
        - path: environments/*
        - path: environments/prod
          exclude: true
  template:
    metadata:
      name: 'weather-{{path.basename}}'
    spec:
      project: weather-dev
      source:
        repoURL: https://github.com/zachseifts/argocd-test.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
