apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata: 
  name: testing-dev
  namespace: argocd
spec:
  description: A development testing environment.
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - name: '*'
    namespace: '*'
    server: https://kubernetes.default.svc
  sourceRepos:
  - https://github.com/zachseifts/argocd-test.git
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: testing-dev
spec:
  generators:
  - git:
      repoURL: https://github.com/zachseifts/argocd-test.git
      revision: HEAD
      directories:
        - path: overlays/*
        - path: overlays/prod
          exclude: true
  template:
    metadata:
      name: 'testing-{{path.basename}}'
      labels:
        app.kubernetes.io/name: 'testing-{{path.basename}}'
        app.kubernetes.io/instance: '{{path.basename}}'
    spec:
      project: testing-dev
      source:
        repoURL: https://github.com/zachseifts/argocd-test.git
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
