apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: weather-dev
spec:
  generators:
  - list:
      elements:
      - cluster: prod
        url: https://kubernetes.default.svc
        namespace: weather-prod
  template:
    metadata:
      name: '{{cluster}}-weather-prod'
    spec:
      project: default
      source:
        repoURL: https://github.com/zachseifts/argocd-test.git
        targetRevision: HEAD
        path: environments/{{cluster}}
      destination:
        server: '{{url}}'
        namespace: '{{namespace}}'
        syncOptions:
        - CreateNamespace=true
