apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata: 
  name: testing-prod
  namespace: argocd
spec:
  description: A production testing environment.
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - name: '*'
    namespace: '*'
    server: https://kubernetes.default.svc
  sourceRepos:
  - https://github.com/zachseifts/argocd-test.git
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: testing-prod
spec:
  generators:
  - list:
      elements:
      - cluster: prod
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: 'testing-{{cluster}}'
    spec:
      project: testing-prod
      source:
        repoURL: https://github.com/zachseifts/argocd-test.git
        targetRevision: HEAD
        path: environments/{{cluster}}
      destination:
        server: '{{url}}'
        namespace: 'testing-{{cluster}}'
      syncPolicy:
        automated:
          prune: true
