apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: testing
resources:
  - cache.yaml
  - backend.yaml
configMapGenerator:
  - name: testing-cache-config
    files:
      - config/cache-config
patches:
  - target:
      kind: ConfigMap
      name: testing-cache-config
    patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: testing-cache-config
        labels:
          app.kubernetes.io/component: backend
  
