apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: base-testing
resources:
  - admin.yaml 
  - frontend.yaml 
  - backend.yaml 
  - ingress.yaml 
  - redis.yaml 
commonLabels:
  app: weather
  env: prod
