apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: testing
resources:
configMapGenerator:
  - name: testing-cache-config
    files:
      - config/cache-config
patchesStrategicMerge:
  - patches/patch-testing-cache-config.yaml
