resources:
  - ../../base
patches:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: admin-ingress
    path: ingress.yaml
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: frontend-ingress
    path: ingress.yaml
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: backend-ingress
    path: ingress.yaml
