resources:
  - ../../base
patches:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: 
       - admin-ingress
       - backend-ingress
       - frontend-ingress
    path: ingress.yaml
